const productTypes = {
    SAVE_TRANSACTION: "SAVE_TRANSACTION",
    PLUS_TRANSACTION: "PLUS_TRANSACTION",
    MIN_TRANSACTION: "MIN_TRANSACTION",
    DEL_TRANSACTION: "DEL_TRANSACTION",
    HISTORY_TRANSACTION: "HISTORY_TRANSACTION"
}

export default productTypes;